services:
    GaylordP\UserMessengerBundle\Controller\UserMessengerController:
        tags: ['controller.service_arguments']
        autoconfigure: true
        autowire: true

    GaylordP\UserMessengerBundle\Form\UserMessengerConversationMessageType:
        arguments:
            - '@security.helper'
            - '@GaylordP\UserMediaBundle\Repository\UserMediaRepository'
        tags:
            - 'form.type'

    GaylordP\UserMessengerBundle\Provider\UserMessengerProvider:
        arguments:
            - '@security.helper'
            - '@GaylordP\UserMessengerBundle\Repository\UserMessengerConversationMessageRepository'
            - '@GaylordP\UserMessengerBundle\Repository\UserMessengerConversationUserRepository'

    GaylordP\UserMessengerBundle\Repository\UserMessengerConversationRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserMessengerBundle\Repository\UserMessengerConversationMessageRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserMessengerBundle\Repository\UserMessengerConversationUserRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    GaylordP\UserMessengerBundle\Twig\Extension:
        arguments:
            - '@security.helper'
            - '@twig'
            - '@GaylordP\UserMessengerBundle\Provider\UserMessengerProvider'
            - '@GaylordP\UserMessengerBundle\Repository\UserMessengerConversationRepository'
        tags:
            - 'twig.extension'
